// Version and Build Information
// 版本和构建信息
// Auto-generated by update-version.sh

window.VOCAB_HELPER_VERSION = {
  version: '1.0.0',
  buildDate: '2025-11-30',
  gitCommit: '948f421',
  mode: 'API', // API模式（已移除Mock）
  features: [
    'ECDICT词典 (340万词)',
    '智能评分算法',
    '自适应学习',
    '离线同步队列',
    'JWT认证'
  ]
};

// 获取版本信息的便捷方法
window.getVersionInfo = function() {
  const v = window.VOCAB_HELPER_VERSION;
  return `v${v.version} (${v.buildDate}) [${v.gitCommit}]`;
};

// 获取完整版本横幅
window.getVersionBanner = function() {
  const v = window.VOCAB_HELPER_VERSION;
  return `
╔═══════════════════════════════════════════╗
║   👻 Spooky Vocab - 智能英语学习助手       ║
║                                           ║
║   Version:    ${v.version.padEnd(29)} ║
║   Build Date: ${v.buildDate.padEnd(29)} ║
║   Commit:     ${v.gitCommit.padEnd(29)} ║
║   Mode:       ${v.mode.padEnd(29)} ║
║                                           ║
║   Features:                               ║
${v.features.map(f => `║   • ${f.padEnd(37)} ║`).join('\n')}
║                                           ║
╚═══════════════════════════════════════════╝
  `.trim();
};
