// Version and Build Information
// 版本和构建信息
// Auto-generated by update-version.sh

window.VOCAB_HELPER_VERSION = {
  version: '1.0.9',
  buildDate: '2026-01-03',
  gitCommit: '',
  mode: 'API', // API模式（已移除Mock）
  features: [
    'ECDICT词典 (340万词)',
    '智能评分算法',
    '自适应学习',
    'Kuroneko Auth SDK 登录',
    '长期 Refresh Token',
    '链接文本不处理翻译',
    '点击任意位置关闭翻译窗口',
    '手机端关闭按钮',
    '复习工具链接'
  ]
};

// 获取版本信息的便捷方法
window.getVersionInfo = function() {
  const v = window.VOCAB_HELPER_VERSION;
  return `v${v.version} (${v.buildDate}) [${v.gitCommit}]`;
};

// 获取完整版本横幅
window.getVersionBanner = function() {
  const v = window.VOCAB_HELPER_VERSION;
  return `
╔═══════════════════════════════════════════╗
║   👻 Spooky Vocab - 智能英语学习助手       ║
║                                           ║
║   Version:    ${v.version.padEnd(29)} ║
║   Build Date: ${v.buildDate.padEnd(29)} ║
║   Commit:     ${v.gitCommit.padEnd(29)} ║
║   Mode:       ${v.mode.padEnd(29)} ║
║                                           ║
║   Features:                               ║
${v.features.map(f => `║   • ${f.padEnd(37)} ║`).join('\n')}
║                                           ║
╚═══════════════════════════════════════════╝
  `.trim();
};
